### ISSUE TITLE
Are there any plans to support dataview or tasks?

### ISSUE THREAD

**Issue by aoout** [YukiGasai/obsidian-todo-widget#15]

**Comment by aoout** [comment]
In fact, I have also thought about developing a obsidian plugin to collect all tasks into one file in plain text, but it would be difficult to synchronize changes in this way.

**Comment by Druzco** [comment]
I support this request, the widget works much better than others I found, it is interactive and scrollable, and the refresh works (after syncing). However, my current daily todo list is created with dataview. If supporting dataview is difficult, what could be a workaround?

**Comment by aoout** [comment]
@Druzco 
I don't understand Android development at all, but I'm guessing that supporting dataview is difficult. I don’t think we can have any particularly good solutions based on the current code.

**Comment by YukiGasai** [comment]
Hi,
I asked in the obsidian discord server.
Sadly there is no API to get the dataview results without running obsidian directly so this feature is not possible. 
I understand that a lot of people use dataview and the tasks plugin to curate their to-dos, but without running obsidian these plugins can't run and their functionality would have to be programmed into the widget directly.

**Comment by Druzco** [comment]
He, thanks for your effort and explanation!

**Comment by aoout** [comment]
> there is no API to get the dataview results without running obsidian directly so this feature is not possible.  without running obsidian these plugins can't run and their functionality would have to be programmed into the widget directly.

that's what i'm worried about. I might try to figure out how to develop a new obsidian todo plugin to go with it.

**Comment by Druzco** [comment]
I decided to look at existing plan apps for which integration with Obsidian exists. For Todoist one exists, and that app has a quite a nice widget to show daily tasks, they can be checked off and somewhat edited, and have a link that opens the particular file in Obsidian. I might be partial, since I used Todoist before Obsidian. Its called 'Ultimate Todoist Sync'.
