### ISSUE TITLE
Dynamic Path Support ?

### ISSUE THREAD

**Issue by yant0** [YukiGasai/obsidian-todo-widget#3]
I have my notes in `Month/ daily notes`. How would i access it

**Comment by YukiGasai** [comment]
You should be able to use the date placeholder in paths as well.

Example:

`Daily/2023/09/07.md`

PATH:
`..../Daily/{{yyyy}}/{{MM}}/`

Filename:
`{{dd}}`

**Comment by yant0** [comment]
Yep it works thanks
