### ISSUE TITLE
Widget does not display tasks from Dataview Queries

### ISSUE THREAD

**Issue by ForeverFloating** [YukiGasai/obsidian-todo-widget#4]
The widget only displays "No todos" if the file only has Dataview queries to display tasks. When I add a task manually in the page, the widget displays that task correctly, but still does not include any Dataview queries to tasks.

**Comment by YukiGasai** [comment]
Hi,
the widget can only display tasks that are written inside the selected file.
When using dataview the the tasks are loaded by the plugin during the runtime. 
Because the widget has no access to that function it's not possible to display tasks gathered by dataview.
