### ISSUE TITLE
Always "No todos"

### ISSUE THREAD

**Issue by mhaendler** [YukiGasai/obsidian-todo-widget#9]
Hey sorry to bother you. 

I was browsing the web and found your .apk as it is exactly what i am looking for.

Unfortunatly i don't get it to work on my Samsung Galaxy A50.

Everything is setup, like in your Demo.mp4 file, i can click the "daily note for example 2023-10-19" and
obsidian opens the correct file with my todo's in it. 

But your widget only display's "No todos". Can you assist me in fixing the issue?

In the documents i only have an "info.txt" with the following contents

[2023-10-19 15:14:06]:TODOS | Loading the count 
[2023-10-19 15:14:06]:TODOS | Reset the count 
[2023-10-19 15:14:06]:TIMER | Loading the count 
[2023-10-19 15:14:06]:TIMER | Reset the count 
[2023-10-19 15:14:16]:TIMER | Loading the count 
[2023-10-19 15:14:16]:TIMER | Increment the count to 1

Unfortunatly there aren't any error's.

**Comment by YukiGasai** [comment]
Hi,
what version of Android are you using?
Have you allowed the storage permission the main application asked for?
Could you share your config, so I can try to recreate your setup?

**Comment by mhaendler** [comment]
Hey Yuki,

sure here are all information i can provide:

* Android Version 11
* One UI-Version 11

ObsidianTodo-Widget has File Persmission.

* Vault name: DriveSyncFiles

* Folder: /DriveSyncFiles/daily/

* File-Name: {{yyyy-MM-dd}}

My Folder is shared / synced with DriveSync to sync my files between multiple devices. Not sure if that matters :)

**Comment by YukiGasai** [comment]
I recreated your exact setup, and unfortunately it works in my emulator.
I believe the app is not able to parse your todos.
Could you give an excerpt of your daily note without the real content, of course?

**Comment by mhaendler** [comment]
Yes of course, i mean there isn't much in it: 

* [x] Test 1 

I also tried it like this:

# Todos
* [ ] Test 2

**Comment by YukiGasai** [comment]
Hi,
if you use this syntax by chance
~~~
* [ ] Task
~~~

Please try this one
~~~
- [ ] Task
~~~

**Comment by mhaendler** [comment]
I found the issue, the problem wasn't anything file related.

After entering the file format "{{yyyy-MM-dd}} " there was a trailing whitespace... 

And yes, you also have to use the 
```
- [ ] Task
```

Thank you very much, for helping me debugging the issue....
